name = "Track"
uuid = "62b9129b-677e-4bae-ad6d-cef5d3fb1fc8"
authors = ["Vitor <vitor.souza@lnls.br>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
